schedules:
- cron: "3 3 3 * *"
  displayName: Monthly Build
  branches:
    include:
    - master

stages:
- template: azure/stages.yml@templates
  parameters:
    minrust: 1.35.0
    codecov_token: $(CODECOV_TOKEN_SECRET)

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: crate-ci
